name: Add to team
on:
  issue_comment:
    types: [created]

jobs:
  process-application:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------------------
      # 1️⃣ Set up Node (we’ll run a short JS script)
      # --------------------------------------------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install @actions/github helper
        run: npm i @actions/github@latest

      - name: Install @actions/core helper
        run: npm i @actions/core@latest

      # --------------------------------------------------------------
      # 2️⃣ Core logic
      # --------------------------------------------------------------
      - name: Verify, add, comment & close
        env:
          REQUIRED_ORG: EpicGames
          TARGET_ORG: Fluppisoft
          TARGET_TEAM_SLUG: brick-rigs-modders
          # ------------------------------------------------------------------
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node <<'EOF'
          const core = require('@actions/core');
          const github = require('@actions/github');

          const token = process.env.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);
          const ctx = github.context;
          const commentBody = github.context.payload.comment.body.trim();

          // --------------------------------------------------------------
          // Information about the issue & its author
          // --------------------------------------------------------------
          const issueNumber = ctx.payload.issue.number;
          const repoOwner   = ctx.repo.owner;
          const repoName    = ctx.repo.repo;
          const applicant   = ctx.payload.issue.user.login;   // issue creator

          // --------------------------------------------------------------
          // Helper: post a comment on the issue
          // --------------------------------------------------------------
          async function comment(body) {
            await octokit.rest.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber,
              body,
            });
          }

          // --------------------------------------------------------------
          // Helper: close the issue
          // --------------------------------------------------------------
          async function closeIssue() {
            await octokit.rest.issues.update({
              owner: repoOwner,
              repo: repoName,
              issue_number: issueNumber,
              state: 'closed',
            });
          }

          // --------------------------------------------------------------
          // 2️⃣ Add user to TARGET_TEAM
          // --------------------------------------------------------------
          async function addToTeam() {
            await octokit.rest.teams.addOrUpdateMembershipForUserInOrg({
              org: process.env.TARGET_ORG,
              team_slug: process.env.TARGET_TEAM_SLUG,
              username: applicant,
              role: 'member',
            });
          }

          // --------------------------------------------------------------
          // 3️⃣ Main flow
          // --------------------------------------------------------------
          (async () => {
            try {
              if (commentBody !== '/next') {
                await comment(
                  `Closing due to unexpected comment.`
                );
                await closeIssue();
                return;
              }

              await addToTeam();
              await comment(
                `✅ @${applicant}, you have been added to the modding team! Go here to download the latest BRMK version: https://github.com/Fluppisoft/BrickRigsModKit/releases `
              );
              await closeIssue();
            } catch (err) {
              console.error(err);
              await comment(
                `⚠️ An error occurred while processing your request: ${err.message}`
              );
              await closeIssue();
            }
          })();
          EOF
