name: Add Issue Author to Team
on:
  issues:
    types: [closed]
jobs:
  add-to-team:
    if: github.event.issue.state_reason == 'completed'
    runs-on: ubuntu-latest
    steps:
      - name: Check if closed by moderator
        id: moderator_check
        uses: actions/github-script@v7
        with:
          script: |
            const moderators = ['Fluppi393'];
            const closer = context.payload.sender.login;
            return moderators.includes(closer);
      - name: Add author to team
        if: steps.moderator_check.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const author = context.payload.issue.user.login;
            const team_slug = 'brick-rigs-modders';
            await github.request('PUT /orgs/{org}/teams/{team_slug}/memberships/{username}', {
              org: context.repo.owner,
              team_slug,
              username: author
            });

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "You have been invited to the Brick Rigs modding team! Please check your email or GitHub notifications. After accepting the invite, you will be able to find the latest releases here: https://github.com/Fluppisoft/BrickRigsModKit/releases"
            });
