name: Issue Auto Comment
on:
  issues:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add automated comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your application. Please follow these steps to join the Epic Games organization on GitHub: https://www.unrealengine.com/en-US/ue-on-github. We will get back to you as soon as possible."
            })
